version: "3.9"

services:
  cookie_clicker:
    #build: .
    image: ghcr.io/oolunar/cookieclicker:latest
    restart: unless-stopped
    environment:
    - CookieClicker__CookieTracker__Period=""
    - CookieClicker__Database__ApplicationName=""
    - CookieClicker__Database__DatabaseName=""
    - CookieClicker__Database__Host=""
    - CookieClicker__Database__Password=""
    - CookieClicker__Database__Port=""
    - CookieClicker__Database__Username=""
    - CookieClicker__Discord__ApplicationId=""
    - CookieClicker__Discord__GithubUrl=""
    - CookieClicker__Discord__PublicKey=""
    - CookieClicker__Discord__Token=""
    - CookieClicker__Discord__UserAgent=""
    - CookieClicker__Logging__Level=""
    - CookieClicker__Logging__Overrides__Microsoft.EntityFrameworkCore=""
    - CookieClicker__Server__Address=""
    - CookieClicker__Server__BasePath=""
    - CookieClicker__Server__Port=""
    - CookieClicker__Server__RequestMemoryLimit=""
    - CookieClicker__Server__RequestReadTimeout=""
    ports:
    - 8080:80