// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OoLunar.CookieClicker.Database;

#nullable disable

namespace CookieClicker.Migrations
{
    [DbContext(typeof(CookieDatabaseContext))]
    partial class CookieDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OoLunar.CookieClicker.Entities.Cookie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("_clicks")
                        .HasColumnType("numeric(20,0)")
                        .HasColumnName("clicks");

                    b.HasKey("Id")
                        .HasName("pk_cookies");

                    b.ToTable("cookies", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
